### ISSUE TITLE
Port timestamp fix for Alerting in plugin version v1.x 

### ISSUE THREAD

**Issue by sahnib** [grafana/opensearch-datasource#100]
Grafana users running v8.x are not able to configure alerts in OpenSearch. See https://community.grafana.com/t/alert-for-opensearch-datasource-gets-wrong-value/64088 for details. Seems like this is related to timestamp parsing and the issue was fixed post v2.0.1 in PR: https://github.com/grafana/opensearch-datasource/commit/11de7384c94a8671dab7fa13d08d645e1e20480a and https://github.com/grafana/opensearch-datasource/pull/66/files.

OpenSearch plugin v2.x depend on Grafana >= 9.0.0. Can we backport the timestamp fixes to OpenSearch plugin version 1.2 so that the issue is fixed in Grafana v8.x?

**Comment by svennergr** [comment]
Thanks @sahnib. This was indeed [backported](https://github.com/grafana/opensearch-datasource/pull/64) and [released in v1.2.1](https://github.com/grafana/opensearch-datasource/releases/tag/v1.2.1).
