### ISSUE TITLE
Create test trace data and ingest it into a test instance of Open Search in aws

### ISSUE THREAD

**Issue by sarahzinger** [grafana/opensearch-datasource#105]
Worth checking to see if we already have something like this set up, but we need a way to create a view traces in open search. 

Assuming we do not already have a test instance of open search service in aws with valid traces, we will likely need to:
- make some kind of test app that is instrumented with open telemetry
- then we need someway to collect and format that data and send it to an instance of open search (ideally one that is deployed in aws, so we can share between team members) to be ingested.

In this pre-req section there's some talk on how to do this: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/trace-analytics.html although it's possible there might be better sample apps already. They mention X-Ray I wonder if it's possible to use the same test apps we have from x-ray and send that data to open search somehow? I think theoretically it should also be easy to sort of fake a trace if we know the proper format, as opensearch can ingest data with a curl script, but is probably best long term to have a test app with real traces we can play with. 

found another test data app here: https://opensearch.org/docs/2.6/observing-your-data/trace/getting-started/

more helpful info here: https://docs.google.com/document/d/1l8HYKvCddF9jUdkAV0TkHU6fsWFs8T1s-gLWbaGLtog/edit

**Comment by fridgepoet** [comment]
Some notes:
* Used the bulk movies sample from https://docs.aws.amazon.com/opensearch-service/latest/developerguide/search-example.html
* Followed this tutorial to create the OpenSearch domain https://docs.aws.amazon.com/opensearch-service/latest/developerguide/gsg.html

**Comment by iwysiu** [comment]
Further notes: 
- Attempted both the guide that Shirley found and the workshop that guide was created from and was not able to get them working.
- Development is possible with just local traces
- After talking to AWS about it, they have been made aware the guides don't work and suggest running the local steps (cloning the example repo, running docker) in an aws instance instead.

**Comment by fridgepoet** [comment]
Let us know if you want us to look into this!
