### ISSUE TITLE
Error switching between Moving Average > Options > Model 

### ISSUE THREAD

**Issue by fridgepoet** [grafana/opensearch-datasource#108]
**What happened**:
Getting a Query error `OpenSearch error: Could not parse settings for model ____` (for example [ewma]) when switching from a Model with more settings (Beta/Gamma) to Model with less settings (just Alpha, for example).

**How to reproduce it (as minimally and precisely as possible)**:
1. open the opensearch datasource in explore
2. you should see a working "count" metric query
3. add another metric, choose moving_avg. configure it:
field: choose count
in options, choose model=holt-linear
set some values, for example:
window=5, predict=2, alpha=0.1, beta=0.2
4. Now switch back to options > model > exponentially weighted
5. Should see the query error. 

See video below for the reproduction:

https://github.com/grafana/opensearch-datasource/assets/4163034/eec4e872-e25e-4703-bfa2-dcc932c44ed6

**Environment**:
- Grafana version: v10.1.0-pre
- Plugin version: v2.6.2

**Comment by fridgepoet** [comment]
I am still able to reproduce this issue

**Comment by katebrenner** [comment]
closing as not planned
