### ISSUE TITLE
Opensearch plugin doesn't support using Grafana configured time zone for ES queries

### ISSUE THREAD

**Issue by thislyc** [grafana/opensearch-datasource#109]
While using Grafana for data visualization, I noticed that the Opensearch plugin doesn't support using the time zone configured in Grafana for ES queries. Regardless of how I change the time zone settings in Grafana, the Opensearch plugin always uses the UTC time zone for queries.

Expected result: The Opensearch plugin should support using the time zone configured in Grafana for ES queries to ensure data accuracy and consistency.

Steps to reproduce:

Set different time zones in Grafana, such as UTC+8, UTC-5, etc.
Create a panel based on the Opensearch data source and set the time zone to "auto".
Observe the time range and display of the query results.
Actual result: Regardless of the time zone set in Grafana, the Opensearch plugin always uses the UTC time zone for queries, resulting in inaccurate or inconsistent data.

Suggested solution: Add support for using the time zone configured in Grafana for ES queries to the Opensearch plugin to ensure data accuracy and consistency. An option can be added in the plugin settings to allow users to choose whether to use the time zone configured in Grafana for ES queries. Additionally, updating the plugin documentation to explicitly state that the plugin doesn't support using the time zone configured in Grafana for ES queries can be considered.

**Comment by sarahzinger** [comment]
@thislyc thanks for reporting your issue, we're trying to recreate it on our end. Do you know:
- What version of Grafana you're running
- What version of the open search plugin you're running?
- What sort of  timerange you have selected (ex: relative time of last 5 min vs a specific time selection)

I looked in main grafana and noticed there does seem to be an open issue around relative timezones, so it's possible you're running into that?: https://github.com/grafana/grafana/issues/59665

I believe this plugin works the same as all grafana plugins in which it:
- takes the selected time range in the user's timezone and converts that to the same time selection but in the utc equivalent
- a query is then made with that utc selection
- the results are then shown in to the user in the user's timezone

Can you explain more how converting a query to UTC and back would result in inaccurate or inconsistent data? I would expect the opposite?

**Comment by thislyc** [comment]
> * What version of Grafana you're running
v9.2.5

> * What version of the open search plugin you're running?
2.1.0



> * What sort of timerange you have selected (ex: relative time of last 5 min vs a specific time selection)

last 6 hour

![image](https://user-images.githubusercontent.com/42378143/224983441-0440ce36-58ea-4fb5-8fc5-b6fbef5f197c.png)
I am in UTC+8 time zone, no matter how I modify the time zone settings on the dashboard
I find that there is always a delay in the data
But the same dashboard uses the ElasticSearch plug-in in grafana 8.5, and there is no time delay

**Comment by thislyc** [comment]
![image](https://user-images.githubusercontent.com/42378143/224984950-ac2eb3d3-6981-452f-bb89-85032a252952.png)
![image](https://user-images.githubusercontent.com/42378143/224985372-33238171-c518-4fc3-a9f2-05fe4c257f8f.png)

**Comment by sarahzinger** [comment]
@thislyc thanks for that! Unfortunately I still haven't been able to reproduce this, so a few more questions:
- how are you running grafana? Is it self hosted, on Grafana Cloud etc?
- can you talk me through your timezone settings for server, organization, team and personal: https://grafana.com/docs/grafana/latest/administration/organization-preferences/#organization-preferences
- Does this seem to happen for all open search queries or a particular type of query?
- What version of opensearch are you running?

**Comment by thislyc** [comment]
> * how are you running grafana? Is it self hosted, on Grafana Cloud etc?
 It self hosted


> * can you talk me through your timezone settings for server, organization, team and personal:

![image](https://user-images.githubusercontent.com/42378143/225568377-52974f20-0af0-443d-ae85-c565a5d5bcee.png)



> * Does this seem to happen for all open search queries or a particular type of query?

all open search queries



> * What version of opensearch are you running?

In fact I don't use opensearch, but ElasticSearch6.5

**Comment by sarahzinger** [comment]
Thanks for that @thislyc one more clarifying q are you running Elastic Search 6.5 through Amazon's Open Search Service or is it self hosted?

**Comment by thislyc** [comment]
> Thanks for that @thislyc one more clarifying q are you running Elastic Search 6.5 through Amazon's Open Search Service or is it self hosted?

Self hosted

**Comment by kevinwcyu** [comment]
Hi @thislyc, we haven't been able to reproduce this yet.

> Create a panel based on the Opensearch data source and set the time zone to "auto".

Do you have a screenshot of setting the time zone to "auto"? For the time zone picker, there's only a "Default" option.

Can you share the dashboard JSON? You can do so as follows:
1. Open the dashboard you want to export.
1. Click the Share icon.
1. Click Export.
1. Toggle on the "Export for sharing externally" option
1. Click Save to file.
