### ISSUE TITLE
Visual Bug when selects are expanded

### ISSUE THREAD

**Issue by sarahzinger** [grafana/opensearch-datasource#110]
**What happened**:
I've noticed when you click to expand certain dropdowns in the query editor such as Options to the right of Metric the other selects are now vertically centered which seems a bit confusing, especially when you click on one and it jumps to be top-aligned

**What you expected to happen**:
I would expect all selects to remain top-aligned

**How to reproduce it (as minimally and precisely as possible)**:
- Open the query editor (I looked at it on explore, but I suspect its the same everywhere)
<img width="981" alt="Screenshot 2023-03-13 at 11 00 33 AM" src="https://user-images.githubusercontent.com/6620164/224741381-b16e699f-984b-49b2-91a3-5f9e587864fb.png">

- Click to expand Options, notice the 2 selects have been pushed down which looks a bit odd
<img width="860" alt="Screenshot 2023-03-13 at 11 00 39 AM" src="https://user-images.githubusercontent.com/6620164/224741335-ddce8c09-bb55-4485-b712-2ff9fcc147be.png">

- Click on one of those selects and notice that it now jumps to be top aligned:
<img width="797" alt="Screenshot 2023-03-13 at 11 00 55 AM" src="https://user-images.githubusercontent.com/6620164/224741699-cdb7a441-5ce9-4f65-ba5c-d46ce942de4b.png">

**Environment**:
- Grafana version: ~ 9.4
- Plugin version: ~ 2.1

**Comment by katebrenner** [comment]
closing as stale
