### ISSUE TITLE
Trace Analytics Data Link issue

### ISSUE THREAD

**Issue by sarahzinger** [grafana/opensearch-datasource#134]
While testing this pr: https://github.com/grafana/opensearch-datasource/pull/122

We noticed that when you open a datalink and click to add another query it doesn't default to the correct datasource:
![Screenshot 2023-04-13 at 10 09 01 AM](https://user-images.githubusercontent.com/6620164/231785617-47be1ec6-9de4-44d1-8396-4903128447d1.png)

**Comment by fridgepoet** [comment]
I think this can be closed, please re-open if I've misunderstood!
