### ISSUE TITLE
Grafana alerts error while dialing: dial unix /tmp/plugin

### ISSUE THREAD

**Issue by llpetkova** [grafana/opensearch-datasource#14]
**What happened:**

After switch of datasource to Opensearch, grafana alerts are pending or failing with error: _tsdb.HandleRequest() error rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /tmp/plugin: connect: connection refused"_

**What you expected to happen:**

The alert to not be failing.

**How to reproduce it (as minimally and precisely as possible):**
Set up a panel with datasource Opensearch. 
The query is as follow:
<img width="1345" alt="Screenshot 2022-01-28 at 09 53 25" src="https://user-images.githubusercontent.com/75635288/151525933-271d5db3-09b6-4a58-a68c-2e4b68d1afda.png">

Then set up an alert:
<img width="864" alt="Screenshot 2022-01-28 at 09 56 53" src="https://user-images.githubusercontent.com/75635288/151526351-f18de4f1-355f-48d0-bc11-e110405951c8.png">

**Anything else we need to know?:**
The queries are returning correct data. The only issue is with the alert.

**Environment:**

Grafana version: grafana/grafana:7.5.10
Data source type & version: OpenSearch  1.0
User OS & Browser:
Grafana plugins: OpenSearch 1.1.1

**Comment by svennergr** [comment]
Hi @llpetkova,

this was most likely resolved in the OpenSearch datasource versions `1.2.1` / `2.0.1.`.

Please open a new issue if this is still an issue for you.
