### ISSUE TITLE
Updating/Opening annotations break the logic and may break the dashboards

### ISSUE THREAD

**Issue by hardikbajaj** [grafana/opensearch-datasource#143]
**What happened**:
Updating or opening an annotation messes up the dashboard logic, and query field becomes empty. This breaks the annotation query logic.

When you add annotation, JSON model of dashboard look like this
<img width="638" alt="Screenshot 2023-04-18 at 11 07 19 AM" src="https://user-images.githubusercontent.com/58038410/232680948-123d097e-7253-485f-9f74-5f6f7b1fe3de.png">

When you just open the annotation or update any field apart from query, JSON model becomes this
<img width="796" alt="Screenshot 2023-04-18 at 11 09 03 AM" src="https://user-images.githubusercontent.com/58038410/232681217-637a0f4e-2fc9-4b9f-b563-552dfa47f494.png">

the `target` field contains the query now, which the annotation don't read and full timeseries panel is filled with annotations at all time stamps. This can break the dashboard in cases where time range is very high.

**What you expected to happen**:
The query field to always contain the query added in UI

**How to reproduce it (as minimally and precisely as possible)**:
- Create an annotation with some query and see JSON model of dashboard for the annotation
- See how the annotation works in your panel (it will work as expected)
- Now open the annotation and update any field apart from query or just open it and change nothing
- Now see the JSON model of dashboard, the `query` will be empty and `target` will contain the query now
- Refresh annotation (by turning on and off annotation) and you'll see all points of timeseries graph filled with annotations. It will not read your lucene query.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.4.7
- Plugin version: 2.2

**Comment by fridgepoet** [comment]
Thanks @hardikbajaj for reporting this. Looks like it is the same as https://github.com/grafana/grafana/pull/66762 (thanks
Gábor for such a nice explanation).

It looks like we will need to make a similar fix.
