### ISSUE TITLE
Placeholder text doesn't change when query type changes

### ISSUE THREAD

**Issue by katebrenner** [grafana/opensearch-datasource#147]
**What happened**:

https://user-images.githubusercontent.com/32871890/232919400-410478bf-7772-400b-9157-cd1e6d7a3d91.mov

**What you expected to happen**:

I expect that when I change the query type, the placeholder text will update to reflect the query type

**How to reproduce it (as minimally and precisely as possible)**:
From explore, shift between Lucene and PPL, and note that the placeholder text in the `QueryField` doesn't update, unless typing a query

**Comment by fridgepoet** [comment]
I'm imagining this is a good first issue, feel free to remove the label!

**Comment by katebrenner** [comment]
closing as not planned
