### ISSUE TITLE
Expressions following pipeline aggregations (derivative) result in Query Error: 500

### ISSUE THREAD

**Issue by blaho-bradley** [grafana/opensearch-datasource#154]
<img width="1458" alt="opensearch_plugin_error" src="https://user-images.githubusercontent.com/121884258/234367792-7b66f406-2d08-43f0-9b72-c9e6a2679990.png">

**What happened**: It looks like any expression (even just $A) following a pipeline aggregation results in this behavior (query 500 error). This is reproducible regardless of whether or not the metric is hidden.

**What you expected to happen**: I expect that the expression would operate each timeseries returned from the query

**How to reproduce it (as minimally and precisely as possible)**:
- Set OpenSearch datasource
- Set Average metric on field / Date Histogram on A
- Add metric "derivative" on Average metric
- Add Expression `$A`
- Observe "Query error: 500"

**Anything else we need to know?**:
This may be related to: grafana [51152](https://github.com/grafana/grafana/issues/51152)

**Environment**:
- Grafana version: v9.2.3
- Plugin version:  v2.4.0

**Comment by idastambuk** [comment]
Hi @blaho-bradley, thanks for reporting this! 
I've managed to reproduce it (albeit with a different error). Currently investigating, will report with any updates or ways to go around it
