### ISSUE TITLE
Document which open-search backed role is required

### ISSUE THREAD

**Issue by sdwerwed** [grafana/opensearch-datasource#155]
Document what role and/or the permissions are needed for connecting the datasource with OpenSearch (self-hosted, not AWS). Currently, we use admin role but we want to switch to read_only role for better security

**Comment by idastambuk** [comment]
Hi @sdwerwed, are you referring to [setting up a read-only user](https://opensearch.org/docs/1.2/security-plugin/access-control/users-roles/#set-up-a-read-only-user-in-opensearch-dashboards) through your OpenSearch dashboard and adding them in Grafana OpenSearchDS with `Basic Auth`, or some other workflow?

**Comment by idastambuk** [comment]
Hi @sdwerwed, any news on if you've managed to use the already existing resources to get the role working?
