### ISSUE TITLE
Backend: Remove use of simplejson

### ISSUE THREAD

**Issue by fridgepoet** [grafana/opensearch-datasource#157]
Similar to what was done in CloudWatch https://github.com/grafana/grafana/pull/51062 

Note: Marking this as a "good first issue" for anyone who would like to contribute any part of this -- the overall work may be significant, but some parts may be straightforward to re-write.

**Comment by DinethShanG** [comment]
I would like to work on this

**Comment by fridgepoet** [comment]
@DinethShanG sounds great, go for it! Feel free to find a way to break it up and make multiple PRs. Let us know if you want any guidance!
