### ISSUE TITLE
Support jumprole for AWS OpenSearch Serverless

### ISSUE THREAD

**Issue by rene84** [grafana/opensearch-datasource#160]
### Discussed in https://github.com/grafana/opensearch-datasource/discussions/159

<div type='discussions-op-text'>

<sup>Originally posted by **rene84** May  2, 2023</sup>
The use-case is that we host our Grafana instance in a different AWS account from where the OpenSearch Serverless collection resides. We would like to access this collection using an assumed IAM role in that account.

This would be very similarly configured to the AWS Cloudwatch datasource, we the datasource can be configured with an IAM role ARN which the datasource assumes using STS before attempting to access the collection.</div>

**Comment by rene84** [comment]
Can anyone please comment on this? @iwysiu maybe?

**Comment by sarahzinger** [comment]
@rene84 I believe we already support this. Do you have [sigv4 enabled](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#sigv4_auth_enabled) in your custom.ini? Also see here: https://github.com/grafana/opensearch-datasource#aws-signature-version-4-authentication

I believe when you do so you should have the ability to assume an IAM role in the configuration settings. 

Let me know if I'm missing anything though!

**Comment by rene84** [comment]
Oh that would be awesome! Going to check

**Comment by sarahzinger** [comment]
@rene84 how's it going? Were you able to get this to work?

**Comment by sarahzinger** [comment]
Going to close this issue due to inactivity, but if you have additional problems feel free to open another issue and we'll take a look thanks!
