### ISSUE TITLE
Requests to MultiSearch endpoint have the wrong "Content-Type" header value

### ISSUE THREAD

**Issue by sivo** [grafana/opensearch-datasource#164]
**What happened**:
Requests to the `_msearch` endpoint between the web UI and the Grafana server/proxy have a "Content-Type" header set to "application/json", although it is newline-delimited JSON.

This normally would work just fine, except in some configurations where there is a reverse proxy in between (nginx in my case) that for some reason doesn't handle this correctly.

**What you expected to happen**:
Requests to the `_msearch` endpoint should have the "Content-Type" header set to "application/x-ndjson". The Elasticsearch datasource does this correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard with a data request using this datasource. Observe headers of the request that is made from the browser when viewing the dashboard.

**Environment**:
- Grafana version: 9.4.7
- Plugin version: 2.2.0

**Comment by kevinwcyu** [comment]
Thanks @sivo, I'll put this into our backlog.

---

Reference PR to whoever picks this up: https://github.com/grafana/grafana/pull/32282
