### ISSUE TITLE
PPL: Unable to create queries without timestamp

### ISSUE THREAD

**Issue by sarahzinger** [grafana/opensearch-datasource#172]
**What happened**:
Right now if you try to make a PPL query with a table format, a timestamp is always inserted regardless of whether or not your dataset has timestamps. 

**How to reproduce it (as minimally and precisely as possible)**:
- go to dev tools in opensearch dashboard: http://localhost:5601/app/dev_tools#/console
- Insert some test data that does not have timestamps, ex from AWS docs:
 ```
 PUT accounts/_bulk?refresh
{"index":{"_id":"1"}}
{"account_number":1,"balance":39225,"firstname":"Amber","lastname":"Duke","age":32,"gender":"M","address":"880 Holmes Lane","employer":"Pyrami","email":"amberduke@pyrami.com","city":"Brogan","state":"IL"}
{"index":{"_id":"6"}}
{"account_number":6,"balance":5686,"firstname":"Hattie","lastname":"Bond","age":36,"gender":"M","address":"671 Bristol Street","employer":"Netagy","email":"hattiebond@netagy.com","city":"Dante","state":"TN"}
{"index":{"_id":"13"}}
{"account_number":13,"balance":32838,"firstname":"Nanette","lastname":"Bates","age":28,"gender":"F","address":"789 Mady Street","employer":"Quility","city":"Nogal","state":"VA"}
{"index":{"_id":"18"}}
{"account_number":18,"balance":4180,"firstname":"Dale","lastname":"Adams","age":33,"gender":"M","address":"467 Hutchinson Court","email":"daleadams@boink.com","city":"Orick","state":"MD"}
 ```
- go to the workbench in opensearch http://localhost:5601/app/opensearch-query-workbench 
- Select PPL and run sample query: `search source=accounts | where age > 18 | fields firstname, lastname`
- notice you get back a table of data
- try to make the same query in the plugin
- Notice you'll get an error message regarding the timestamp in the network tag because the query is always inserting a timestamp into the query: `"search source=accounts | where `@timestamp` >= timestamp('2023-05-15 19:10:52') and `@timestamp` <= timestamp('2023-05-15 20:10:52') | where age > 18 | fields firstname, lastname"`

**Anything else we need to know?**:
we recently added a "[Use time range](https://github.com/grafana/opensearch-datasource/pull/125)" option for Lucene queries. It would be nice to have a similar feature for PPL

**Environment**:
- Grafana version: ~9.4
- Plugin version: ~2.4.1

**Comment by katebrenner** [comment]
closing as stale
