### ISSUE TITLE
Inconsistent results between alerts and queries

### ISSUE THREAD

**Issue by sarahzinger** [grafana/opensearch-datasource#176]
**What happened**:
I see different results between alerts and queries

**What you expected to happen**:
to see the same results

**How to reproduce it (as minimally and precisely as possible)**:
- I added the following test data to opensearch with [devtools](http://localhost:5601/app/dev_tools#/console):
```
PUT testdata/_bulk?refresh
{"index":{"_id":"1"}}
{"testdata_number":1,"value": 3, "@timestamp": 1684332772392  }
{"index":{"_id":"6"}}
{"testdata_number":6,"value": null, "@timestamp": 1684332772399 }
```

I then made the following query:
![Screenshot 2023-05-17 at 10 47 10 AM](https://github.com/grafana/opensearch-datasource/assets/6620164/457d772c-7993-4872-8f64-cc1843efe330)

I then tried to create an alert for that query and saw that the data is missing:
![Screenshot 2023-05-17 at 10 48 00 AM](https://github.com/grafana/opensearch-datasource/assets/6620164/3cbdc2cc-7b40-46f7-b36e-39987161ecfd)

when I remove the lucene query string, I can see data but I can't seem to filter it at all and sucessfully get data to show. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: ~9.4
- Plugin version: ~2.4.1

**Comment by fridgepoet** [comment]
@sarahzinger Would you consider this done?
