### ISSUE TITLE
Investigate Supporting Jaeger Trace Data

### ISSUE THREAD

**Issue by sarahzinger** [grafana/opensearch-datasource#193]
[We recently released support for Trace Analytics,](https://github.com/grafana/opensearch-datasource/releases/tag/v2.4.0) but all of our test data for that project used Data Prepper, and that is 1 of 2 ways people use Trace Analytics with open search. The other [involves storing Jaeger Data in OpenSearch directly](https://opensearch.org/docs/latest/observing-your-data/trace/trace-analytics-jaeger/). 

Let's investigate what would be involved to support this. If it seems like a larger project we should write out a Design Doc. I haven't taken a deep look at this yet, but I wouldn't be surprised if we already support this, or we just need to make a small change like update an index somewhere. 

This ticket involves:
- creating test data that stores jaeger data directly into opensearch and documenting the two ways here: https://github.com/grafana/opensearch-datasource/tree/main/devenv#how-to-set-up-local-development-environment-to-work-with-traces-in-open-search
- validating that jaegar data already works
- if it doesn't work determine what needs to be changed, if it's a small effort, that can be captured here, or if it's a bigger lift, let's close this ticket once the design doc is made and create a separate Epic for it.

**Comment by sarahzinger** [comment]
Probably makes sense to revisit this after our [migration](https://github.com/grafana/oss-plugin-partnerships/issues/194) so putting this in the backlog for now

**Comment by katebrenner** [comment]
closing as not planned - duplicate of https://github.com/grafana/opensearch-datasource/issues/384
