### ISSUE TITLE
Backend: Migrate PPL Logs queries to the backend

### ISSUE THREAD

**Issue by idastambuk** [grafana/opensearch-datasource#200]
Prerequisite: https://github.com/grafana/opensearch-datasource/issues/226

PPL Logs are processed into dataFrames on the FE, and as timeSeries on the BE. They should probably be separated out.
ES plugin doesn't support PPL queries, but maybe the [Logs PR](https://github.com/grafana/grafana/pull/63647) for Lucene could be something to look at for reference.

Some general guidelines are:

* Create visualization to compare between frontend and backend flows, preferably in a shared Cloud dashboard e.g. clouddatasources.grafana.net 
* Unit tests in the frontend should be copied or updated in the backend to assert the same behavior and add unit tests when there are none.
    * Check Elasticsearch repo for related tests – helpful when there are no OpenSearch tests in the frontend or backend
* We should match OpenSearch's backend behavior to the current frontend behavior, but be aware it may not always make sense. Elasticsearch's current behavior is also another resource for how OpenSearch should behave.
    * Let's be pragmatic about this – our foremost goal is the migration of OpenSearch's frontend behavior. We can aim for some Elasticsearch feature parity, but only _within reason_.
* Often there is a PR in the Elasticsearch backend data source migration [https://github.com/grafana/grafana/issues/54011](https://github.com/grafana/grafana/issues/54011) which is 75% of what OpenSearch will need
* Migrate or implement: i.e. make any changes to code in backend
* Use the dashboard created above to compare visualization results (data frame comparison)
    * Can also inspect data frame on a more detailed basis
   
  
Note: ([Similarly](https://github.com/grafana/opensearch-datasource/issues/199) to Lucene Logs of the FE) It looks like PPL Logs are not completely correctly processed on the Frontend, as the int field is passed as string. This isn't the case on the BE, as seen from the screenshot. 
<img width="500" alt="Screenshot 2023-06-12 at 1 31 26 PM" src="https://github.com/grafana/opensearch-datasource/assets/16140639/2a3ec0da-f082-4b87-8de4-048367cf78a5">
<img width="300" alt="Screenshot 2023-06-12 at 1 32 18 PM" src="https://github.com/grafana/opensearch-datasource/assets/16140639/2c801a51-312b-4311-8551-c4314ac7457a">

**Comment by sarahzinger** [comment]
maybe we can also fix this one: https://github.com/grafana/opensearch-datasource/issues/212 with this ticket
