### ISSUE TITLE
PPL queries not working with timestamp filters

### ISSUE THREAD

**Issue by iwysiu** [grafana/opensearch-datasource#212]
If you try to use a PPL query with a timestamp filter, it doesn't return any data despite the data existing. Note that this only happens for timestamps.

I reproduced this with the local `jaeger-hotrod` setup and the ppl query `source = security-auditlog-2023.07.12` (note that you'll need to change this to a day where you with data)

After investigating, it seems like we're not converting the timezones correctly/ shouldn't be converting them. When I filter by `audit_request_remote_address` it sends the following query to the _ppl endpoint and successfully filters the data:
```
source = security-auditlog-2023.07.12 | where `@timestamp` >= timestamp('2023-07-12 06:31:29') and `@timestamp` <= timestamp('2023-07-12 18:31:29') | where `audit_request_remote_address` = '172.25.0.5'
```
![Screenshot 2023-07-12 at 2 31 36 PM](https://github.com/grafana/opensearch-datasource/assets/5421859/279a1eb5-43d1-4c9a-be82-d7f170d62c4f)

And the query that doesn't return data when filtering by timestamp. Note the difference between the timezone in the picture and the sent query:

```
source = security-auditlog-2023.07.12 | where `@timestamp` >= timestamp('2023-07-12 07:06:18') and `@timestamp` <= timestamp('2023-07-12 19:06:18') | where `@timestamp` = timestamp('2023-07-12 13:45:03.654000')
```

<img width="799" alt="Screenshot 2023-07-12 at 3 08 04 PM" src="https://github.com/grafana/opensearch-datasource/assets/5421859/39755d0d-4836-4cba-a7a1-40d34cbc3d59">

Trying the above query in in the OpenSearch observability tab fails, but if I change it to match the displayed value it works: 

![Screenshot 2023-07-12 at 3 23 07 PM](https://github.com/grafana/opensearch-datasource/assets/5421859/0aa12e4a-1b6e-4d07-b2a4-442a8ac160a2)

Additional notes:
This was originally reported in https://github.com/grafana/support-escalations/issues/6700
I think there's a separate issue with fetching filter values that's also happening here, but I'll file a separate issue for that.

**Comment by reagankan** [comment]
Hello! 

Any updates on whether this issue will be worked on? 

AMG customers are hoping for a fix. Thank you!

**Comment by iwysiu** [comment]
Hi @reagankan ! This issue is actually at the top of our next column, and should be worked on soon.
