### ISSUE TITLE
Timestamp filter values aren't being fetched correctly

### ISSUE THREAD

**Issue by iwysiu** [grafana/opensearch-datasource#213]
**What happened**:
When fetching filter values, we call [getTerms](https://github.com/grafana/opensearch-datasource/blob/6718c3779868d451a9b0461455fbaa9f632cc114/src/datasource.ts#L873C8-L873C8) without a range value, which means that when timestamp values are fetched they're always from the default range.

**What you expected to happen**:
I expect it to fetch all and only the values from the range

**How to reproduce it (as minimally and precisely as possible)**:
Create a PPL query (local traces with the ppl query `source = security-auditlog-2023.07.12` but replace the auditlog date with a day with data) and click filter for value for a timestamp value. If you open the filter dropdown/check the network tab, you should see that it's using the default range.

**Anything else we need to know?**:
Even after fixing this, filtering on a timestamp still won't work until https://github.com/grafana/opensearch-datasource/issues/212 is fixed.

**Environment**:
- Grafana version:
- Plugin version:

**Comment by reagankan** [comment]
Hello!

Any updates on whether this issue will be worked on in the near future?

AMG customers are hoping for a fix. Thank you!
