### ISSUE TITLE
Variable filter not working in Grafana panel when we select raw data. its working with term

### ISSUE THREAD

**Issue by lalitdhami007** [grafana/opensearch-datasource#219]
**What happened**:
Filter in table not working with Grafana variable

**What you expected to happen**:
Filter Should work in table when we select option from variable dropdown value

**How to reproduce it (as minimally and precisely as possible)**:
Create any index with 10 number of record
create data source with opensearch indices 
create variable
and create a table panel with lucane query 
![image](https://github.com/grafana/opensearch-datasource/assets/81741142/14f300ae-b5d5-441e-a62a-c56007d2fc3f)
no data is comming 

if we hardcode value then its working
![image](https://github.com/grafana/opensearch-datasource/assets/81741142/e62715d7-62c4-4b6d-8c26-d22382c057ff)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9 and 10
- Plugin version: 2.8.0

**Comment by fridgepoet** [comment]
Hi @lalitdhami007 thanks so much for raising this issue.
I've reproduced the problem -- it should be present starting from v2.7.0 due to the work in https://github.com/grafana/opensearch-datasource/pull/203. 

We'll work on a fix.
In the meantime you should be able to use v2.6.2 without this issue.

**Comment by lalitdhami007** [comment]
Thanks for taking this bug in which version we would get fixed. now we are moving back to 2.6

**Comment by fridgepoet** [comment]
Just released [v2.8.1](https://github.com/grafana/opensearch-datasource/releases/tag/v2.8.1) with the fix. Thanks again for bringing up the issue!

**Comment by lalitdhami007** [comment]
![image](https://github.com/grafana/opensearch-datasource/assets/81741142/a8435df5-bf9b-41e6-8513-0c47df9c9364)
now its working thanks again for fixing this issue
