### ISSUE TITLE
ad hoc filters not applied to raw_data queries

### ISSUE THREAD

**Issue by gulecroc** [grafana/opensearch-datasource#224]
**What happened**:

Use a table with raw data.

When adding a filter from ad hoc filter, the table must filter lines.

Or when adding a filter from the table (clic on button "+" to add the key/value as an ad hoc filter).

![image](https://github.com/grafana/opensearch-datasource/assets/8898737/27aa92dd-2bcf-4403-8575-4f32451c07f4)

I have 2 problems :
- when adding filter from the ad hoc filter on the top, there is no value _Edit: this has been separated [to another issue](https://github.com/grafana/opensearch-datasource/issues/227) now_
- when adding filter from the table value (clic on button "+" to add the key/value filter), the table is not filtered

**What you expected to happen**:

The table content is filtered with ad hoc filter.

**How to reproduce it (as minimally and precisely as possible)**:

Create opensearch data :

```
DELETE /grafana_table_raw_data_ad_hoc_filters

PUT grafana_table_raw_data_ad_hoc_filters

POST /grafana_table_raw_data_ad_hoc_filters/_bulk
{"index":{}}
{"name": "test0", "filter1": "value1", "@timestamp" : "2023-07-26"}
{"index":{}}
{"name": "test1", "filter1": "value1", "@timestamp" : "2023-07-26"}
{"index":{}}
{"name": "test2", "filter1": "value1", "@timestamp" : "2023-07-26"}
{"index":{}}
{"name": "test3", "filter1": "value2", "@timestamp" : "2023-07-26"}
{"index":{}}
{"name": "test4", "filter1": "value2", "@timestamp" : "2023-07-26"}
{"index":{}}
{"name": "test5", "filter1": "value2", "@timestamp" : "2023-07-26"}
{"index":{}}
{"name": "test6", "filter1": "value3", "@timestamp" : "2023-07-26"}
{"index":{}}
{"name": "test7", "filter1": "value3", "@timestamp" : "2023-07-26"}
{"index":{}}
{"name": "test8", "filter1": "value3", "@timestamp" : "2023-07-26"}
{"index":{}}
{"name": "test9", "filter1": "value4", "@timestamp" : "2023-07-26"}
```

Add grafana opensearch datasource from this index.

Create a simple dashboard with table and raw data :

![image](https://github.com/grafana/opensearch-datasource/assets/8898737/e75b003c-56ad-4e73-9ae8-40cbdb7b5ebf)

Select on the button "+" near a table line value to create the ad hoc filter.

**Anything else we need to know?**:
This bug was introduced in v2.7.0

**Environment**:
- Grafana version: v9.5.6 (859a2654d3)
- Plugin version: 2.8.1

**Comment by fridgepoet** [comment]
Hi @gulecroc, thanks for reporting this issue. I can reproduce it and we'll work on a fix.
In the meantime you can roll back to v2.6.2 of the plugin and it should work again.

**Comment by gulecroc** [comment]
Hi @fridgepoet , thank you for your reply.

I create an elasticsearch datasource with opensearch URL and it works.
If I create the filter from the top, I have option values only from "key.keyword", not from "key".
If I create the filter from selecting value in the table, the filter key name is "key" :

![image](https://github.com/grafana/opensearch-datasource/assets/8898737/27fc720a-2d65-4e86-be32-6343186a05c3)

**Comment by gulecroc** [comment]
I rollback the plugin to v2.6.2.

The filter from selecting value in the table works well.
But adding filter at the top does not show values, using "key" or "key.keyword" :

![image](https://github.com/grafana/opensearch-datasource/assets/8898737/47295e7c-d35b-4929-9afb-1c50fddc7f09)

![image](https://github.com/grafana/opensearch-datasource/assets/8898737/9ac6d522-7321-4f21-ad3d-f74122d271aa)

**Comment by fridgepoet** [comment]
Thanks @gulecroc, on any previous version of the opensearch plugin, were you ever able to show the values from adding the filters?

**Comment by gulecroc** [comment]
I @fridgepoet , sorry for the delay I was on vacation.
No problem to create multiples issues.
Thank you for your work !

**Comment by fridgepoet** [comment]
no worries @gulecroc, hope you had a nice vacation! thanks so much for reporting issues!
