### ISSUE TITLE
Values not listed when adding filter from the ad hoc filter

### ISSUE THREAD

**Issue by fridgepoet** [grafana/opensearch-datasource#227]
First reported in https://github.com/grafana/opensearch-datasource/issues/224

**What happened**:
> when adding filter from the ad hoc filter on the top, there is no value

Clicking on the value should show a list of populated possible values. It shows "No options found"
![Screenshot 2023-07-26 at 16 42 52](https://github.com/grafana/opensearch-datasource/assets/4163034/aac4cc91-e40e-494e-b1d5-c05194b2272e)

**What you expected to happen**:
Clicking on the value should show a list of populated possible values.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a raw_data query (should be available here https://clouddatasources.grafana.net/goto/qWWCp8q4R?orgId=1 with Last 1 year time range which is populated with sample Flight data from OpenSearch).
2. Click Edit
3. Click on a (+) spyglass next to one of the values to show the ad hoc filters
4. Click on the value
Expected: A list of possible values should appear
Actual: "No options found" is displayed

**Anything else we need to know?**:
A workaround is simply to enter in the value you'd like to filter. This should still work. Only the listing of the possible values is not working.

**Environment**:
- Grafana version: 10
- Plugin version: confirmed in v2.8.1, v2.6.2, probably all versions -- seems to never have been available

**Comment by iwysiu** [comment]
Fixed in https://github.com/grafana/opensearch-datasource/issues/213
