### ISSUE TITLE
release for arm64

### ISSUE THREAD

**Issue by patrat** [grafana/opensearch-datasource#24]
Hello,

We are running on AWS Graviton2 and wanted to ask if it would be possible to have a release for arm64 as well.

Thanks!

**Comment by AlKapkone** [comment]
Yes. I'm also waiting for the arm64 release! Thanks a lot, forehand!

**Comment by svennergr** [comment]
Hi @patrat and @AlKapkone,

we recently changed to a new CI. By doing that, we are now also building ARM64 binaries.
You'll find them [here](https://github.com/grafana/opensearch-datasource/releases).
