### ISSUE TITLE
values reported in `explore` dont match actual values

### ISSUE THREAD

**Issue by mhristof** [grafana/opensearch-datasource#242]
**What happened**:
I've got a dashboard that shows metricbeat memory usage
```
host.hostname: "$instance" AND agent.type: "metricbeat" AND process.name:* AND metricset.name: process
```
and the dashboard drop all values to 0 after GMT 00:00 

![image](https://github.com/grafana/opensearch-datasource/assets/24205462/3b18fd50-c2cd-45b4-a845-9c6669d7e70c)

![image](https://github.com/grafana/opensearch-datasource/assets/24205462/d61ee714-814d-4bf6-b3c0-b38226ce95e3)**What you expected to happen**:

If i explore the raw data, the values are OK

![image](https://github.com/grafana/opensearch-datasource/assets/24205462/e4b9cf99-b703-415e-ad27-9c145237b75e)

**How to reproduce it (as minimally and precisely as possible)**:
Not sure

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v9.5.8 (4c140fd26e)
- Plugin version: 2.9.0

**Comment by kevinwcyu** [comment]
Hi @mhristof, I'm trying to reproduce this, but have been unable to so far.

- Can you show me the query that's executed? You can do so by clicking on the "Inspector" button in the query editor when you're in the explore view, then click on the "Query" tab, and click "Refresh". Could you provide what that shows with any sensitive info redacted.
- Also could you let me know what version of OpenSearch you're using?

**Comment by mhristof** [comment]
Query thats executed: https://gist.github.com/mhristof/7379e2e516b9f8f88c447f6b0458a238
opensearch version:2.5
This was working for version `2.8.2`, then it broke as im showing on the graph and then i bumped to `2.9.0` to see if that solves the issues.

**Comment by fridgepoet** [comment]
Hi @mhristof we've been unable to reproduce your issue locally on the latest `2.9.0` on Grafana v9.5.8. 
Were you saying it was working at some point in `2.8.2` and then later stopped working in the same version `2.8.2`?

Let us know if you have any more instructions on reproducing this.

What behavior do you see in the OpenSearch Dashboards on the same data? 

For information, I've tried is querying the ["sample flight data"](https://opensearch.org/docs/latest/dashboards/quickstart/) in a period over 24 hours to see if any of the values have dropped to 0.

**Comment by mhristof** [comment]
It was working for `2.8.2`, then it broke, then i upgraded to `2.9.0` to check if it made the issue go away.

Unfortunately i dont have any more instructions on how to reproduce this. Could i run any kind of debug-log heavy build to see if that will return anything interesting ? 


> What behavior do you see in the OpenSearch Dashboards on the same data?

The opensearch dashboards report the proper data. In the description, i've added the data view from when i explore the data source and i can see the proper values.

![image](https://github.com/grafana/opensearch-datasource/assets/24205462/e8f09bfc-f1db-4c5c-9893-872154cc6b47)

**Comment by fridgepoet** [comment]
We're not aware of what could have happened if it was working in `2.8.2` and then broke in the same version.

I wasn't able to reproduce your issue on `OpenSearch 2.5` with sample data. Are you able to reproduce this with sample data? https://opensearch.org/docs/latest/dashboards/quickstart/
