### ISSUE TITLE
Unable to create Alert Rule with OpenSearch Plugin "plugin unavailable"

### ISSUE THREAD

**Issue by rlueckl** [grafana/opensearch-datasource#251]
**What happened**: while trying to create an alert rule which uses the OpenSearch datasource plugin I get an error that the plugin is unavailable.

**What you expected to happen**: creating the alert rule works without errors.

**How to reproduce it (as minimally and precisely as possible)**:
  * install grafana-opensearch-datasource (I used grafana-cli)
  * setup a datasource which uses OpenSearch
  * go to *Home > Alerting > Alert rules > Add rule* in Grafana
  * under *2 Define query and alert condition* choose your OpenSearch datasource and write a simple query
  * click on *Preview*

**Anything else we need to know?**:
Clicking on Preview brings the following error in the GUI:

![Screenshot at 2023-09-06 08-48-59](https://github.com/grafana/opensearch-datasource/assets/10848041/00897c77-a8b1-4426-8a14-1e8d8fbeb77c)

![Screenshot at 2023-09-06 08-49-07](https://github.com/grafana/opensearch-datasource/assets/10848041/11a0e963-1358-4cb4-843e-f4f406987cb9)

In the logs I see the same error (remote_addr removed for privacy):
`logger=context userId=1 orgId=1 uname=admin t=2023-09-06T06:24:36.358454764Z level=info msg="Failed to evaluate queries and expressions: [sse.dataQueryError] failed to execute query [A]: [plugin.unavailable] plugin unavailable" error="Failed to evaluate queries and expressions: [sse.dataQueryError] failed to execute query [A]: [plugin.unavailable] plugin unavailable" remote_addr=X.X.X.X traceID=`

Plugin was installed with `grafana-cli` and Grafana runs in a Docker/Kubernetes environment.
```
/etc/grafana/plugins/grafana-opensearch-datasource $ ls -la
total 25804
drwxr-xr-x    3 grafana  root          4096 Aug 25 06:53 .
drwxr-xr-x    1 grafana  root          4096 Aug 25 06:53 ..
-rw-r--r--    1 grafana  root          4805 Aug 25 06:53 CHANGELOG.md
-rw-r--r--    1 grafana  root         11355 Aug 25 06:53 LICENSE
-rw-r--r--    1 grafana  root          1648 Aug 25 06:53 MANIFEST.txt
-rw-r--r--    1 grafana  root         18952 Aug 25 06:53 README.md
-rwxr-xr-x    1 grafana  root          2510 Aug 25 06:53 go_plugin_build_manifest
-rwxr-xr-x    1 grafana  root      25501696 Aug 25 06:53 gpx_opensearch-datasource_linux_amd64
drwxr-xr-x    2 grafana  root          4096 Aug 25 06:53 img
-rw-r--r--    1 grafana  root        249428 Aug 25 06:53 module.js
-rw-r--r--    1 grafana  root           149 Aug 25 06:53 module.js.LICENSE.txt
-rw-r--r--    1 grafana  root        600154 Aug 25 06:53 module.js.map
-rw-r--r--    1 grafana  root           979 Aug 25 06:53 plugin.json
/etc/grafana/plugins/grafana-opensearch-datasource $ 
```

`grafana.ini`:
```
[plugin.opensearch]
path = /etc/grafana/plugins/grafana-opensearch-datasource
```
The OpenSearch datasource is working fine in all other regards, I can create dashboards with it, no problem. **Only alert rules are affected.**

**Environment**:
- Grafana version: 10.1.0
- OpenSearch version: 2.9.0
- Plugin version: 2.9.0

**Comment by idastambuk** [comment]
Hi @rlueckl! 
I'm afraid I cannot reproduce the issue; however, when I install the plugin via grafana-cli, it gets put into var/lib/ directory
``` Downloaded and extracted grafana-opensearch-datasource v2.10.0 zip successfully to /var/lib/grafana/plugins/grafana-opensearch-datasource``` and it works without any custom configuration in grafana/ini

Did you run `grafana cli plugins install grafana-opensearch-datasource` with any additional arguments?

**Comment by rlueckl** [comment]
I've installed the plugin with the following command:

```
$ grafana-cli --pluginsDir "/etc/grafana/plugins" plugins install grafana-opensearch-datasource
Deprecation warning: The standalone 'grafana-cli' program is deprecated and will be removed in the future. Please update all uses of 'grafana-cli' to 'grafana cli'
✔ Downloaded and extracted grafana-opensearch-datasource v2.9.0 zip successfully to /etc/grafana/plugins/grafana-opensearch-datasource

Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.
```

Unfortunately I have to install it under `/etc`, this is a limitation in our environment, that's why I need the additional configuration in `grafana.ini`. All plugins worked so far with this method.

The OpenSearch plugin also works when using it in dashboards, panels or in "Explore". Only the alert rules seem affected.

**Comment by idastambuk** [comment]
Hi @rlueckl thanks for the info! I just wanted to install the plugin in the same way, as this is an error that happens when plugin is unreachable due to a build issue. Unfortunately I'm still unable to reproduce your error in alerts, even after following the same steps. 

1. Is there anything else custom about the environment you're running grafana in? Just a thought: Have you tried restarting the container to see if that fixes the issue? I came across the same bug that was "fixed" by a restart so I wonder they have the same cause.
2. The metrics query you're running above - if you run it in explore, does it return data? Also wondering if it might be the size of the response that makes it fail. 
3. You mentioned you have other datasources installed. Do alert Previews return data for your other datasources?

**Comment by rlueckl** [comment]
Hi @idastambuk,

1. I don't think so. Grafana is running in our Kubernetes. The only thing I can think of is the read-only root filesystem. I've tried restarting/redeploying the pods, but that didn't help.
2. The same query works in Explore and when creating a new panel in a Dashboard. See screenshots below. The query is fairly simple and returns the results within a few milliseconds.
3. Other datasources work fine and are returning data for alert previews. I've tested it with the built-in Elasticsearch plugin, Graphite and Prometheus.

I've tried setting Grafana log level to debug, but that didn't get me more usable logs unfortunately:

```
logger=accesscontrol.service t=2023-09-08T06:58:13.445991783Z level=debug msg="fetch permissions from store" key=rbac-permissions-1-user-1
logger=accesscontrol.service t=2023-09-08T06:58:13.451042712Z level=debug msg="cache permissions" key=rbac-permissions-1-user-1
logger=accesscontrol.evaluator t=2023-09-08T06:58:13.451742818Z level=debug msg="matched scope" userscope=datasources:* targetscope=datasources:uid:aeb35fa9-****-****-****-31095692ee07
logger=datasources t=2023-09-08T06:58:13.451913296Z level=debug msg="Querying for data source via SQL store" uid=aeb35fa9-****-****-****-31095692ee07 orgId=1
logger=secrets.kvstore t=2023-09-08T06:58:13.456738064Z level=debug msg="got secret value" orgId=1 type=datasource namespace=logstash-XXXXXX
logger=expr datasourceType=grafana-opensearch-datasource queryRefId=A datasourceUid=aeb35fa9-****-****-****-31095692ee07 datasourceVersion=5 t=2023-09-08T06:58:13.457008655Z level=debug msg="Data source queried" responseType=error
logger=context userId=1 orgId=1 uname=admin t=2023-09-08T06:58:13.457111742Z level=info msg="Failed to evaluate queries and expressions: [sse.dataQueryError] failed to execute query [A]: [plugin.unavailable] plugin unavailable" error="Failed to evaluate queries and expressions: [sse.dataQueryError] failed to execute query [A]: [plugin.unavailable] plugin unavailable" remote_addr=X.X.X.X traceID=
logger=context userId=1 orgId=1 uname=admin t=2023-09-08T06:58:13.457843638Z level=error msg="Request Completed" method=POST path=/api/v1/eval status=500 remote_addr=X.X.X.X time_ms=19 duration=19.478174ms size=160 referer="https://[internal-grafana-address]/alerting/new/alerting?returnTo=%2Falerting%2Flist" handler=/api/v1/eval
```

![opensearch_dashboard_query](https://github.com/grafana/opensearch-datasource/assets/10848041/add61144-fd36-4fe0-8354-3103f985bb9e)

![opensearch_explore_query](https://github.com/grafana/opensearch-datasource/assets/10848041/10625bad-27bb-4327-a218-db240bdaef11)

**Comment by rlueckl** [comment]
A little more testing and I've found these logs right when Grafana is starting up:

```
logger=plugin.loader t=2023-09-11T12:31:21.074768964Z level=info msg="Plugin registered" pluginID=grafana-opensearch-datasource
logger=plugin.grafana-opensearch-datasource t=2023-09-11T12:31:21.099759058Z level=error msg="plugin init error" error="open /tmp/plugin22351235: read-only file system"
logger=plugin.grafana-opensearch-datasource t=2023-09-11T12:31:21.101478271Z level=info msg="plugin process exited" path=/etc/grafana/plugins/grafana-opensearch-datasource/gpx_opensearch-datasource_linux_amd64 pid=48
logger=plugin.loader t=2023-09-11T12:31:21.101647663Z level=error msg="Could not start plugin" pluginId=grafana-opensearch-datasource err="Unrecognized remote plugin message: \nThis usually means\n  the plugin was not compiled for this architecture,\n  the plugin is missing dynamic-link libraries necessary to run,\n  the plugin is not executable by this process due to file permissions, or\n  the plugin failed to negotiate the initial go-plugin protocol handshake\n\nAdditional notes about plugin:\n  Path: /etc/grafana/plugins/grafana-opensearch-datasource/gpx_opensearch-datasource_linux_amd64\n  Mode: -rwxr-xr-x\n  Owner: 472 [grafana] (current: 1000 [?])\n  Group: 0 [root] (current: 0 [root])\n  ELF architecture: EM_X86_64 (current architecture: amd64)\n"
```

I've seen something similar while googling for this issue in the Zabbix plugin repository: https://github.com/grafana/grafana-zabbix/issues/1604

This is very interesting, since the plugin *is working* with Dashboards and Explore.

Regarding the read-only filesystem `/tmp/plugin22351235: read-only file system` I'll have to try out if giving some temp. space will help or not.

**Comment by rlueckl** [comment]
Yes! That read-only filesystem was the problem.

Making `/tmp` a writable location (I set it to an `emptyDir` Volume(Mount) in the K8s Deployment) did the trick. Now I can create alert rules without any errors.

Maybe the README.md should mention the fact that the plugin needs a writable `/tmp`.

It would be even better if the location could be configured somehow? Or maybe it is already and I didn't found it in the docs?

**Comment by fridgepoet** [comment]
Nice @rlueckl !!

We'd love for the experience to be clearer. Would you like to open a PR with a suggested improvement to the README? Or let us know specifically what we should advise.

**Comment by rlueckl** [comment]
Quite honestly I'm not sure what I could write into the README. I'm not even sure why a writable `/tmp` directory is needed for this plugin, but not for the other plugins.

I'm *guessing* that it has something to do with the binary file `gpx_opensearch-datasource_linux_amd64`. I'm also *guessing* that this binary is started by Grafana itself and sometime during startup wants to write something to `/tmp` - as this message suggests when trying to execute the file manually:

```
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

I have no idea why the plugin wants to write to `/tmp` or if that location is configurable in any way - through the plugin or through Grafana itself? Could the plugin use Grafana's "data" directory which is defined in `grafana.ini`: `paths.data`? I don't know.
