### ISSUE TITLE
Backend Migration: Remove Lucene Logs Explore-only restriction (condition is in frontend)

### ISSUE THREAD

**Issue by fridgepoet** [grafana/opensearch-datasource#275]

**Comment by kevinwcyu** [comment]
Done with https://github.com/grafana/opensearch-datasource/issues/373 (effort tracked in this ticket), https://github.com/grafana/opensearch-datasource/issues/372 and https://github.com/grafana/opensearch-datasource/issues/290

**Comment by kevinwcyu** [comment]
Reopening as this was reverted and needs to be reenabled.

**Comment by kevinwcyu** [comment]
Will be done in https://github.com/grafana/opensearch-datasource/issues/407
