### ISSUE TITLE
Dockerized Grafana and Opensearch datasource CORS config 

### ISSUE THREAD

**Issue by Ierlandfan** [grafana/opensearch-datasource#281]
**What happened**:
Access set to "Server(Default)
When using opensearch as datasource for Graylog it says (In the datasource settings) "Unexpected error" when I press "Get version"

When inspecting the page I see in the console:

`Access to fetch at 'https://graylog.x.y.z/' (redirected from 'https://grafana.xyz/api/datasources/proxy/17//') from origin 'https://grafana.xyz' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. `

**What you expected to happen**:
No cors issue to happen
**How to reproduce it (as minimally and precisely as possible)**:
Access set to "Server(Default)
When using opensearch as datasource for Graylog it says (In the datasource settings) "Unexpected error" when I press "Get version"
Even when setting url to IP it still want to use the dns name instead of the IP.

**Anything else we need to know?**:
According to the dosc we can set CORS related setting in opensearch.yml but that file is not present in the Docker. 
Or should I set it on the Graylog nginx config?

**Environment**:
- Grafana version:
- OpenSearch version:
- Plugin version:

**Comment by Ierlandfan** [comment]
Found out that I had to modify the nginx config on graylog server:

Added:

   add_header Access-Control-Allow-Origin '*';
   add_header Access-Control-Allow-Private-Network 'true';
   add_header Access-Control-Allow-Credentials 'true';
   add_header Access-Control-Allow-Headers 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,x-grafana-org-id,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,';
   add_header Access-Control-Allow-Methods 'GET,POST,OPTIONS,PUT,DELETE,PATCH';
   
   But shouldn't that be handled by setting "Server (Default) in datasource?

**Comment by idastambuk** [comment]
Hi @Ierlandfan, thanks for submitting this! It's great you managed to get it working. 
We will move this to our backlog and investigate further. Will update this ticket once we have more info.

**Comment by katebrenner** [comment]
Hi @Ierlandfan wold you mind providing your environment so we have more information when investigating?

Environment:

Grafana version:
OpenSearch version:
Plugin version:
