### ISSUE TITLE
Alert for OpenSearch Datasource no data and timestamp have wrong value

### ISSUE THREAD

**Issue by JaKourdi** [grafana/opensearch-datasource#31]
Visualization worked.

However, alerting is not working as expected. It shows no data:

Visualization:
![image](https://user-images.githubusercontent.com/48384761/170245711-faf9cbe2-91fb-4413-a8b0-38f763d6a582.png)

Alerting --> no Data and the timestamp value is incorrect.

![image](https://user-images.githubusercontent.com/48384761/170245897-8d6ecbf6-3f35-4736-a5f0-ae54a790e78b.png)

This issue was also reported on Grafana's Community:
https://community.grafana.com/t/alert-for-opensearch-datasource-gets-wrong-value/64088

**Comment by adamdougal** [comment]
I get the same issue when trying to use this in an expression. Timestamps return back as:
```
                [
                  -1586166633859,
                  -1499766633859,
                  -1413366633859
                ],
```

Outside of an expression, things work correction and return:
```
                [
                  1658620800000,
                  1658707200000,
                  1658793600000
                ],
```

**Comment by adamdougal** [comment]
We've done a bit of digging, it looks like the issue could lie in this function:

```go
func nullFloatToNullableTime(ts null.Float) *time.Time {
	if !ts.Valid {
		return nil
	}

	sec, fract := math.Modf(ts.Float64)
	nsec := int64(fract * float64(time.Second))
	timestamp := time.Unix(int64(sec), nsec)
	return &timestamp
}
```

https://github.com/grafana/opensearch-datasource/blob/main/pkg/opensearch/response_parser.go#L649-L658

It's assuming the timestamp is in seconds, whereas it looks like it's returned as milliseconds from ElasticSearch.

What would the suggested fix be? Happy to raise a PR.

**Comment by adamdougal** [comment]
@svennergr Heya! This is a bit of a blocker for us so we're happy to contribute if you can help with the direction :)

**Comment by svennergr** [comment]
Hi @adamdougal,

sorry for the delay here. We got a fix in https://github.com/grafana/opensearch-datasource/pull/61 now. This need to sit there until next week, but then we are going to release a new version with a fix.

**Comment by adamdougal** [comment]
Perfect thanks!

**Comment by janisbiz** [comment]
Hi! I am still having same problem on grafana `8.5.13` and OS DS plug-in of `1.2.2`. Alerts basically return:
```
{
  ...
  "logs": [
    ...
    {
      "message": "Condition[0]: Query Result",
      "data": {
        "fromDataframe": true,
        "series": []                                          
      }
    },
    {
      "message": "Condition: Eval: false, Query Returned No Series (reduced to null/no value)",
      "data": null
    }
  ]
}
```

**Comment by svennergr** [comment]
@janisbiz could you add a bit more context if possible? 

E.g. what's the query and where are you executing it? I assume in a dashboard, but it might also be in alerting.

**Comment by janisbiz** [comment]
Hi @svennergr,

I have a panel in dashboard:
![image](https://user-images.githubusercontent.com/19405629/195355438-edfb9f26-ad2c-4503-aedb-e78854c5fdf1.png)
which then has alert defined:
![image](https://user-images.githubusercontent.com/19405629/195355752-c742bbb7-b2a2-411b-8e9f-1a164583e764.png)

As you can see in screenshot - it is alerting. Once I press the "test button" it returns empty series I mentioned [here](https://github.com/grafana/opensearch-datasource/issues/31#issuecomment-1276005779)

If this is not sufficient, let me know.

**Comment by svennergr** [comment]
@JaKourdi Could you please open a new issue providing details about your Grafana version, OpenSearch datasource version and if you are using "classic" Alerting or [new/unified Alerting](https://grafana.com/blog/2021/06/14/the-new-unified-alerting-system-for-grafana-everything-you-need-to-know/)?

**Comment by janisbiz** [comment]
@svennergr did you mean to ping me to open issue or smth? I am a bit confused now :sweat_smile:

**Comment by svennergr** [comment]
@janisbiz exactly. I have difficulties reproducing this, thus it would be good to get a [new issue](https://github.com/grafana/opensearch-datasource/issues/new) describing the bug.

**Comment by janisbiz** [comment]
@svennergr created - https://github.com/grafana/opensearch-datasource/issues/78
