### ISSUE TITLE
Let me configure how many rows i want returned

### ISSUE THREAD

**Issue by havedill** [grafana/opensearch-datasource#329]
I've tried all sorts of queries in grafana yet i cant get more than 200 rows to return with PPL, and 500 with Lucene

https://community.grafana.com/t/ppl-and-changing-the-results-limit-opensearch/113772

Can someone please give me some insight on the proper way to increase this?

**Comment by emirhanese** [comment]
There is a configuration for result size limit. By default in OpenSearch it's 200 but, you can change that using the configuration. You can find the configuration in OpenSearch documentation.

**Comment by havedill** [comment]
Care to link that documentation? Everything i find only references setting it while directly querying the API and specifying the size value

**Comment by havedill** [comment]
Much appreciated thank you

**Comment by katebrenner** [comment]
Thanks @havedill for asking this question and thanks @emirhanese for your responses.  Closing this issue.
