### ISSUE TITLE
Backend migration - Forward OAuth authentication stops working after 2.13

### ISSUE THREAD

**Issue by mimek** [grafana/opensearch-datasource#330]
**What happened**:
After upgrading to version 2.13.0 of the plugin, query from "Explore view" to OpenSearch stopped working. We used "Forward OAuth" option in datasource configuration to authenticate to OpenSearch.

Dashboards visualisations which uses OpenSearch datasource still works fine.

**What you expected to happen**:
Consistent behaviour of querying through "Explore view" and Dashboard. When you configure datasource and test, connectivity test is saying that everything works fine, but if you choose "Explore view" then queries are not working (in debug logs there's visible 401 error while connecting to OpenSearch). After adding configured datasource to dashboard it's working again.

**How to reproduce it (as minimally and precisely as possible)**:
Configure opensearch datasource with "Forward OAuth" option enable (Opensearch must be also configured to support this authentication mechanism) and go to "Explore view" and execute some query.
![image](https://github.com/grafana/opensearch-datasource/assets/6304986/e487c288-0219-4dbf-9475-6a958288652e)

Then try to add same OpenSearch datasource to dashboard and see that's working there.
![image](https://github.com/grafana/opensearch-datasource/assets/6304986/aa6a1102-1eca-4c22-bdda-d82b98dcf864)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.5.15, 10.3.1
- OpenSearch version: 2.11.1
- Plugin version: 2.13

**Comment by iwysiu** [comment]
Hi @mimek ! Thanks for reporting this issue.

For more detail on what's happening, we've done some refactoring of the Opensearch plugin, and currently the Explore and Dashboard queries are running through different paths in case of bugs like this, I'll move it to our backlog to be fixed.

Investigation notes for the person who fixes this:
It looks like (unlike the frontend path) the `httpclient.Provider` we're using for backend queries doesn't automatically forward oauth tokens. We should set `ForwardHTTPHeaders` on the http options to true and it should be passed. See the [developer notes](https://grafana.com/developers/plugin-tools/create-a-plugin/extend-a-plugin/add-authentication-for-data-source-plugins#forward-oauth-identity-for-the-logged-in-user)

**Comment by mimek** [comment]
Hi @iwysiu for explanations and confirming that it should be fixed!

**Comment by idastambuk** [comment]
Hi @mimek we just released v2.14.5 of the plugin that should fix this issue. Can you confirm that your explore queries work with Forward Auth with the new version? Thanks!
