### ISSUE TITLE
opensearch plugin on aws managed grafana fails with type error

### ISSUE THREAD

**Issue by curuvija** [grafana/opensearch-datasource#348]
**What happened**:

When I use opensearch plugin on AWS managed grafana (version 9.4.7) with plugin version 2.4.x I get this error message:

![image](https://github.com/grafana/opensearch-datasource/assets/9008865/6376d31b-c4b8-4379-b105-703e88c75633)

I had to downgrade opensearch plugin to version 2.13.1 to see results. Even then I don't see results I'd expect. I see table with 2 columns: Time and Count. When I use PPL then I can see the table, but still don't have links on Trace ID to open a specific view for that trace id.

**What you expected to happen**:

I expect Traces plugin to pickup traces and draw it on the screen as you can see here (just an example from Grafana docs):

![image](https://github.com/grafana/opensearch-datasource/assets/9008865/366bbf46-5982-48bb-bb9b-9eb617cba641)

So that I can pick trace id and inspect further:

![image](https://github.com/grafana/opensearch-datasource/assets/9008865/e33dc045-a436-47ca-bb44-471306a9793e)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: AWS
- Grafana version: 9.47
- OpenSearch version: 2.11.x
- Plugin version: 2.14.5

**Comment by kevinwcyu** [comment]
Hi @curuvija, does this only happen in Explore or does it also happen when you're on a Dashboard?

**Comment by curuvija** [comment]
hi @kevinwcyu, thanks for helping me. 

I just checked, it only happens in Explore view. 

![image](https://github.com/grafana/opensearch-datasource/assets/9008865/5712983f-977e-4905-a64c-d833baeef260)

When I hit the link, I'm redirected to the Explore view where I see the Table View is missing:

![image](https://github.com/grafana/opensearch-datasource/assets/9008865/8a151886-f7f8-4d46-ae13-2a453b313644)
