### ISSUE TITLE
Add support for full-range histograms

### ISSUE THREAD

**Issue by wilfriedroset** [grafana/opensearch-datasource#352]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when exploring my logs because I cannot see the full range histograms.
Having full range histograms is really helpful when you need to understand a trend.
The current logs volume is based on the logs seen in the response which is not all logs in the range. Hence the logs volume is not really usable.

![Capture d’écran 2024-03-22 à 09 14 03](https://github.com/grafana/opensearch-datasource/assets/12611310/71f9a6c4-5c51-42db-b74e-401d359d8e4c)

**Describe the solution you'd like**
When is explore mode I would like to have support for full-range histograms for the logs volume.
I believe this feature can be achieve by splitting the API calls, one for the logs volume with the date histogram query and the second one for the logs themselves.

**Describe alternatives you've considered**
In explore you cannot workaround the lack of feature. However you can do it with kibana or graylog.
During my day to day I constantly switch back and forth between Grafana and Graylog, while I would love to be explore both my metrics and my logs all together in a single UI.

Example:
![Capture d’écran 2024-03-22 à 09 24 49](https://github.com/grafana/opensearch-datasource/assets/12611310/93f13ec0-8b74-4e18-9964-a625c3615dac)

**Additional context**
OpenSearch plugin: 2.14.4
Grafana: 10.1.8
OpenSearch: 1.3.14

**Comment by kevinwcyu** [comment]
Thanks for the feature request @wilfriedroset, I've moved this to our backlog.

**Comment by wilfriedroset** [comment]
@kevinwcyu do you have any news about this request 🙏🏾?

**Comment by philveea** [comment]
Hi. Any estimates for when this will be out? This kinda blocks us from using the opensearch datasource.

**Comment by psauvage0** [comment]
Hi,
We got this working on a fork, PR coming soon
![Image](https://github.com/user-attachments/assets/379e563c-9a42-4768-be63-186768875824)
