### ISSUE TITLE
data.timestamp(dateTime) field is not working with Opensearch datasource. 

### ISSUE THREAD

**Issue by SricharanSundar** [grafana/opensearch-datasource#364]
### What happened?

Currently we are migrating all the elasticsearch dashboard to opensearch datasource dashboard.
We are trying to implement a timeseries visualization panel for average response time using AVG aggregation and datehistogram.
For date histogram we are using data.timestamp(mapping type:date and format: epoch Millis) field in the query for the result but its not working. 

If I try with datetime(mapping type:date) field its working.

### What did you expect to happen?

The dashboard need to show the result for time series visualization with any dateTime field. In elasticsearch its worked fine but this is not working in opensearch datasource of grafana. But the same time opensearch datasource is giving the correct result in grafana explorer. 

Why this is not working in the dashboards panels.

This query need to work in dashboard panels as well.

### Did this work before?

Yes in explore but not in the dashboard(opnesearch datasource dashboard)
Its worked in elasricsearch datasource dashboard.

### How do we reproduce it?

1. Fix the datehistogram aggregation to work properly for this field.

### Is the bug inside a dashboard panel?

Yes not working with data.timestamp field.(mapping type:date and format: epoch Millis)

### Environment (with versions)?

Grafana: 10.1.6
OS: Windows
Browser: explorer, chrome 

### Grafana platform?

Other

### Datasource(s)?

Elasticsearch, Opensearch

**Comment by sarahzinger** [comment]
Hi @SricharanSundar Thanks for reporting your issue with the opensearch datasource. 

I have a few follow up questions that I'm hoping will help us understand and reproduce the issue:
- What version of the Opensearch datasource are you using? 
- Am I understanding correctly that the bug appears only appears in the Dashboard but not on the Explore page?

For context we are in the process of major refactor of the plugin, if it works on the Explore page but not dashboards, that makes me think this will be fixed once that refactoring project is over https://github.com/grafana/opensearch-datasource/issues/290

**Comment by SricharanSundar** [comment]
Hi @SricharanSundar Thanks for reporting your issue with the opensearch datasource.

I have a few follow up questions that I'm hoping will help us understand and reproduce the issue:

What version of the Opensearch datasource are you using?
opensearch 1.0.0 in grafana datasource
and in aws - opensearch 2.9 
Am I understanding correctly that the bug appears only appears in the Dashboard but not on the Explore page?
yes

**Comment by SricharanSundar** [comment]
Our Opensearch domain version 2.11 in aws and in grafana datasource of opensearch we are using version 1.0.0.

**Comment by sarahzinger** [comment]
> in grafana datasource of opensearch we are using version 1.0.0

Are you able to please upgrade your version of the plugin to 2.14.7 and tell us if the issue still exists? The [1.0.0](https://github.com/grafana/opensearch-datasource/releases/tag/v1.0.0) version is over 2 years old at this point

@SricharanSundar

**Comment by SricharanSundar** [comment]
> > in grafana datasource of opensearch we are using version 1.0.0
> 
> Are you able to please upgrade your version of the plugin to 2.14.7 and tell us if the issue still exists? The [1.0.0](https://github.com/grafana/opensearch-datasource/releases/tag/v1.0.0) version is over 2 years old at this point
> 
> @SricharanSundar

grafana-opensearch-datasource we are using this installation way.
By the way its working with latest version.

**Comment by sarahzinger** [comment]
Great! Glad it's fixed :)
