### ISSUE TITLE
Unable to parse interval

### ISSUE THREAD

**Issue by wilfriedroset** [grafana/opensearch-datasource#389]
**What happened**:

All panels relying on opensearch plugins and using a standard interval variable encounter an error.

https://github.com/grafana/opensearch-datasource/assets/12611310/13bdb390-d3c0-491e-aead-94eb6faae9da

```
Unable to parse interval [$interval]
```

**What you expected to happen**:

The panels load without any error and the variable used for the interval is replace before sending the request to the backend.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The bug seems to have been introduced in either #375 or #367

**Environment**:
- Grafana version: 10.1.9
- OpenSearch version: 1.3.14
- Plugin version: 1.5.0

**Comment by iwysiu** [comment]
Hi @wilfriedroset ! Thanks for reporting this issue, I've reproduced it and I've moved it to our next column to be looked at soon.

**Comment by idastambuk** [comment]
Hi @wilfriedroset and @tstm, we have reverted the migration with the version 2.15.1 so you can update to that version to fix your dashboards until we're able to solve the problem
