### ISSUE TITLE
Request for Opensearch-prometheus dashboard-json file

### ISSUE THREAD

**Issue by pratikshavyas** [grafana/opensearch-datasource#39]
I am looking for dashboard JSON file to import in grafana having opensearch metrices data. Please help from where can I get the dashboard. 
Also, I found one on https://grafana.com/grafana/dashboards/15178 , however this dashboard json file does not have the latest OpenSearch metrices and was updated 8 months ago.
Kindly share from where can I fetch the latest dashboard-json or when will the updated json be available.

**Comment by svennergr** [comment]
Hi @pratikshavyas,

thanks for the question. Adding a bundled dashboard is currently not foreseen. Feel free to try to reach out to the community member who did the dashboard you mentioned.
