### ISSUE TITLE
Error `too many buckets` not passed on to the user

### ISSUE THREAD

**Issue by idastambuk** [grafana/opensearch-datasource#394]
**What happened**:
Sometimes when the time range is very long (or interval short) and there are several `groupBy` clauses, the user gets an `unknown error` in the response. 
It looks like we actually get a `too many buckets` error form Open Search, but we don't pass it onto the user, so they don't know they should adjust their interval to a higher number (or shorter time range, or adjust the [max_buckets config in OpenSearch](https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/search-settings/)). 

**What you expected to happen**:

The UI to show the real error message. 

**How to reproduce it (as minimally and precisely as possible)**:
<img width="1001" alt="Screenshot 2024-05-23 at 12 24 30" src="https://github.com/grafana/opensearch-datasource/assets/16140639/da70cd5e-58cd-4c2f-b0c4-d2cb231be794">

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- OpenSearch version: 
- Plugin version: 12.15.1

**Comment by danfinn** [comment]
How did you know the error you were getting was for too many buckets?  I might be facing the same issue, I'm getting a similar non descriptive error from opensearch where it appears to report a 500 but there are no 500 beings reported on the opensearch cluster.

**Comment by kevinwcyu** [comment]
Closing as fixed by https://github.com/grafana/opensearch-datasource/pull/401
