### ISSUE TITLE
Visualizations in grafana end up hitting max buckets but the same visualization in kibana works fine

### ISSUE THREAD

**Issue by danfinn** [grafana/opensearch-datasource#406]
**What happened**:

We've been working through the max bucket error in grafana with an opensearch datasource.  Initially I thought the issue was with opensearch however we have bumped that max bucket limit to 65536 and we are still mostly seeing this error (some aggregations now work but most hit this limit and error).  To compare I recreated the same simple visualization in kibana (or whatever the equivalent is called for opensearch) and I don't get any errors and it generates the visualization quickly.  I suspect that the opensearch plugin is doing something differently than kibana that is causing it to hit this limit even with a high setting for the limit.

![Explore_-_Prod-OpenSearch_-_Grafana](https://github.com/grafana/opensearch-datasource/assets/5891946/4fadf69e-77f9-4fde-a420-3238bde9b840)

![Visualize_-_OpenSearch_Dashboards](https://github.com/grafana/opensearch-datasource/assets/5891946/8cb947ba-73f9-4251-af8a-4ed18dbf33a9)

**What you expected to happen**:
visualizations to work without hitting max buckets

**How to reproduce it (as minimally and precisely as possible)**:
Create a simple aggregation in grafana using an opensearch datasource

**Anything else we need to know?**:

**Environment**:
- Grafana version: 10.2.3
- OpenSearch version: 2.9 on AWS
- Plugin version: 2.15.4

**Comment by sarahzinger** [comment]
Hi @danfinn I haven't been able to recreate this yet, so if you find a way to create some test data that we can injest into opensearch to test with that could be helpful. 

I have noticed a couple of things that might help though: 
- in screenshot in the (nongrafana) Opensearch dashboard you're not adding another Data Histogram query I don't think so I think it's one less aggregation than what's in the Grafana dashboard maybe? If you remove the "Then By" clause does that produce the expected results?
- When I open the network tab for the Opensearch dashboard making a similar query I see that Opensearch is making a request to `internal/search/opensearch` which is a different endpoint than the one we have access to `msearch`, so it is possible to me that the internal api and the external api could produce separate results and we can only access the external api: https://opensearch.org/docs/latest/api-reference/multi-search/ if this is the case it might be a question better directed to the team that maintains opensearch.

That said I think this is probably more an issue where what you're querying in the kibana/opensearch visualization dashboard is not an apples-to-apples comparison to what you're querying in grafana. If you find a way to recreate this with a specific set of testdata let us know!

**Comment by danfinn** [comment]
Hi @sarahzinger,

At this point I'm not really able to make much use at all of grafana with this opensearch datasource.  For the most part any time I try to do any simple aggregation using "Then By" I hit the max buckets error in opensearch which I've now increased to the same default setting as elasticsearch.  This seems like very basic functionality that should be working.

I added the date histogram to the kibana visualization.  It drew it quickly and without any errors:
<img width="1840" alt="Screenshot 2024-06-11 at 8 33 15 AM" src="https://github.com/grafana/opensearch-datasource/assets/5891946/ccbcbdc6-ee48-417a-8172-07aad136817d">

Removing the "Then By" clause for date histogram in grafana does get it so grafana returns the data but this data is less useless without being able to see it over time.  In my opinion this is a rather simple simple visualization. 

Kibana seems to be handling this without any issues when it's apples to apples.

Unfortunately I don't have a good way to create a test dataset that could be shared.  I'd be happy to screen share in some way if that was helpful.  Are you able to create visualizations in grafana with an opensearch datasource without having to increase the max bucket setting higher than 65k?

**Comment by sarahzinger** [comment]
Yes, it works for me at 65k, but much of this depends on your data (for example how many terms, what range of time, etc). My understanding is that for the query you just shared, the number of buckets is going to be determined by: 
- the number of terms you have (in my example I only had 3 but maybe you have much more?)
- the time range and interval you are bucketing your data into (which in grafana, if you selected "auto" will be our best guess based on from/to and your screen resolution https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#__interval )

I probably wasn't able to reproduce because my data/requests/screen resolution are probably not quite the same as yours. I was however able to reproduce the error however by setting the max bucket size to 1k. 

<img width="1379" alt="Screenshot 2024-06-11 at 3 00 30 PM" src="https://github.com/grafana/opensearch-datasource/assets/6620164/91a444f6-c0eb-44cc-af62-03c6874f6e40">

but if I manually set the interval to 1m in the query builder, it seems to work for me: 
<img width="1382" alt="Screenshot 2024-06-11 at 3 00 49 PM" src="https://github.com/grafana/opensearch-datasource/assets/6620164/af36e85e-d478-45e0-b9ad-7b8d6245c47c">

Does that help with your issue?

**Comment by danfinn** [comment]
I'm using the same amount of terms as you are, just 3.

Yes, setting the time interval to anything seems to help.  10s, 1m, 5m they all seem to work and I'm not getting the max bucket error.  I've not had to set this before, I'm coming from using elasticsearch and this is my first time using opensearch.  Is it odd that the auto setting for grafana is not working in this situation?

**Comment by sarahzinger** [comment]
Ah, just remembered we have this feature here to set a minimal interval:

<img width="1099" alt="Screenshot 2024-06-12 at 3 24 58 PM" src="https://github.com/grafana/opensearch-datasource/assets/6620164/d6131e38-b07c-4576-bb3b-d96d791f15b3">

you can find it on your datasource instance's configuration page in grafana and try setting it to a time interval that seems to work well for your data, that way you don't need to manually set it per query but it also won't go too fine grained. Let me know if that works for you!

**Comment by danfinn** [comment]
Sorry for the delay, setting that on the datasource does seem to be working.  Thanks for the workaround!
