### ISSUE TITLE
Add support for using the PDC (Private Data Connection) with this datasource

### ISSUE THREAD

**Issue by oc-christopher-billett** [grafana/opensearch-datasource#431]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please can you support the use of the PDC (Private Data Connection) for this datasource. Although it is possible to use the Elasticsearch datasource plugin with its warnings of versions it would be better suited to have this built into the OpenSearch especially as AWS OpenSearch gives you the option to run Opensearch within a private VPC

**Describe alternatives you've considered**
It is possible to use the Elasticsearch Datasource but it's not ideal

**Additional context**
None required

**Comment by njvrzm** [comment]
Thank you for the feature request! I'm going to add it to our backlog to estimate and prioritize.

**Comment by iwysiu** [comment]
Link (grafana only) to the implementation guide: [doc](https://docs.google.com/document/d/1IqYANEnTZ30ENRsWGd-oOf0eM44n8ywfytE4U__JEtQ/edit?usp=sharing)

**Comment by iwysiu** [comment]
Blocked on https://github.com/grafana/opensearch-datasource/issues/442
