### ISSUE TITLE
Service Map renders in Explore but not in the dashboard

### ISSUE THREAD

**Issue by VermaPriyanka** [grafana/opensearch-datasource#455]
**What happened**:
Service Map loads in the Explore view, but does not load in a dashboard with the exact same query.

**What you expected to happen**:
Service Map loads in the dashboard as well. This is flaky, it did appear at one point, but doesn't render anymore.

**How to reproduce it (as minimally and precisely as possible)**:
- Configure an Amazon OpenSearch service data source with trace analytics enabled
- Add a node graph panel to a dashboard, with a trace query.
- Select Service map, with Traces query type.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 10.4.1
- OpenSearch version: 2.15
- Plugin version: 2.18

**Comment by idastambuk** [comment]
Hi @VermaPriyanka, we just published v2.19.0 of the OpenSearch datasource that should contain the fix for this, can you update the plugin and confirm? Thanks!
