### ISSUE TITLE
Unexpected error occur when make a new query in panel.

### ISSUE THREAD

**Issue by karl-sh80** [grafana/opensearch-datasource#493]
**What happened**:
I am using grafana 9.5.21 with the opensearch plugin 2.21.1
I created a new panel with opensearch darasource, but an error occurred from the first query.

"An unexpected error happened
 TypeError: (0, unexpected.isAction) is not a function

+ from plugin v2.20.0, this type error occur.

**What you expected to happen**:
The window where you can register the query normally should be visible.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new panel and select opensearch datasource.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.5.21
- OpenSearch version: 2.17.1
- Plugin version: 2.21.1

**Comment by caviliar** [comment]
have also encountered this issue. we worked around it by pinning the version back to `2.19.1`.
```
grafana-opensearch-datasource 2.19.1
```

(looks like upgrading to the latest 11.3.0 also fixes the bug)
https://github.com/grafana/opensearch-datasource/issues/488

_(previous) Environment:
Grafana version: v10.4.11
OpenSearch version: 2.13
Plugin version: 2.21.1_

**Comment by karl-sh80** [comment]
Hi @idastambuk, I have already applied the workaround to my grafana suggested by @caviliar.
Thank you @caviliar.

**Comment by sfisli** [comment]
any updates ?

**Comment by forrejam** [comment]
I'm still getting this issue. 

Grafana 11.0
Plugin 2.22.2

Has this fix made its way into release yet?

**Comment by kevinwcyu** [comment]
This should be fixed in Plugin version 2.22.3 which was just released.
