### ISSUE TITLE
OpenSearch Plugin in Grafana Uses Old _opendistro Endpoint for PPL, Resulting in 400 Bad Request Error

### ISSUE THREAD

**Issue by Alexadra** [grafana/opensearch-datasource#499]
When attempting to run PPL (Piped Processing Language) queries in Grafana using the OpenSearch plugin, the plugin defaults to using the old Open Distro endpoint (/_opendistro/_ppl). This endpoint results in a 400 Bad Request error because OpenSearch has transitioned to using the newer _plugins folder for PPL queries (/_plugins/_ppl).

**Steps to Reproduce:**

1. Install and configure the latest version of OpenSearch and ensure the SQL/PPL plugin is installed and enabled.
2. Set up Grafana and configure an OpenSearch data source.
3. Attempt to run a PPL query in Grafana, such as:
source=test | where SampleLabel is not null | stats avg(ResponseTime) by SampleLabel
3. Observe the request sent by Grafana to the OpenSearch instance.

**Expected Result:**

Grafana should send the request to the endpoint: http://opensearch-node1:9200/_plugins/_ppl.

Opensearch version 2.18.0
Opensearch plugin version 2.21.2

**Comment by iwysiu** [comment]
Hi @Alexadra ! Thanks for the bug report, I've updated the endpoint and it should be fixed in the next release
