### ISSUE TITLE
Support for Private data source connect

### ISSUE THREAD

**Issue by fryops** [grafana/opensearch-datasource#508]
**Is your feature request related to a problem? Please describe.**
For those who use Grafana Cloud or are migrating to it need a PDC to security connect to on-prem/CoLo endpoints.

**Describe the solution you'd like**
Grafana Cloud users using this datasource should see a `Private data source connect` box to select a remote agent for the connection.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kevinwcyu** [comment]
Hi @fryops, PDC should be supported from version `2.21.0` of the OpenSearch data source.

**Comment by fryops** [comment]
You're 100% right. I forgot to update to the latest version after the migration.
Thank you very much :)
