### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by Elfo404** [grafana/opensearch-datasource#6]
When request fails with error it read "OpenSearch error..." which could be confusing is someone has configured Elastic? For example when testing datasource it shows below even when Elastic is selected:

<img width="384" alt="Screen Shot 2021-10-05 at 08 53 40" src="https://user-images.githubusercontent.com/745532/135974745-b4956115-ddcb-4421-870d-c0f856cd0af7.png">

_Originally posted by @ifrost in https://github.com/grafana/opensearch-datasource/pull/5#discussion_r721940972_

In general we should improve error handling to have better messages.

**Comment by makvac-aws** [comment]
I am getting above error while adding "OpenSearch" data source in grafana.

**Comment by Elfo404** [comment]
hi @makvac-aws can we start with some basic info first? can you describe your configuration (grafana version, plugin version, how are you configuring the datasource)? and is there anything in the logs worth noting?

**Comment by makvac-aws** [comment]
Hi Team,

This is what I have configured. I am using Amazon Managed Grafana.

URL: OpenSearch url
Access: Server(Default)
SigV4: Enabled
Authentication Provider: Workspace IAM Role
Assume Role ARN: AWS Role ARN
Default region: us-east-1
Index name: *
Pattern: Hourly
Time field name: @timestamp
Version: I tried Elasticsearch 7.0+ as well as OpenSearch 1.0x. Both are giving the same error.


Regards,
Chetan Makvana
(E) ***@***.******@***.***>
(M) +91 77740 37191
AISPL | aws.amazon.com
***@***.***
Work hard. Have fun. Make history.

**Comment by Elfo404** [comment]
I'm not sure what version of Grafana and OpenSearch plugin is running on AMG, chan you please check this?
Also, do you have access to any logs? do they contain some useful information?

I don't know much about sigv4, but locally I get the same error if I do not set `skip TLS verify` or if I don't correctly set basic auth for the DS, in that case the error is not raised by grafana but by OpenSearch itself, so can you double check your auth settings? i do not have access to the same environment myself, so it's quite hard to debug

**Comment by makvac-aws** [comment]
Grafana version is 8.0 and ElasticSearch is 7.9. I don't have access to any logs.

I also tried setting skip TLS verify and basic auth, still same error

**Comment by Elfo404** [comment]
@makvac-aws i've been trying to figure out what could be wrong with your setup but it's quite hard without having access to the logs. is there a way we could get them?

**Comment by NeunJa** [comment]
Guys, this is Amazon Managed Services - we do not have Grafana Logs.
