### ISSUE TITLE
Timestamp issues in PPL requests 

### ISSUE THREAD

**Issue by svennergr** [grafana/opensearch-datasource#60]
It seems like, the datasources uses timestamps in local-format when using PPL requests. Those should however be in UTC.

**Comment by matyax** [comment]
Which datasources? Maybe this issue could use a little more details about what needs to be fixed.

**Comment by svennergr** [comment]
Good call @matyax. This is btw a duplicate of https://github.com/grafana/opensearch-datasource/issues/21 and thus can be closed.
