### ISSUE TITLE
Using alerts on panel not working

### ISSUE THREAD

**Issue by janisbiz** [grafana/opensearch-datasource#78]
Hello!

Using alerts on existing panels are not working.

Version(s):
- Grafana `v8.5.13 (38d274060d)`
- OS DS Plugin `1.2.2`
- OS Version `1.3.2`

Example panel:
![image](https://user-images.githubusercontent.com/19405629/196905510-2cc07bba-1d46-41b9-ae54-2aced5a02b57.png)
Example alert:
![image](https://user-images.githubusercontent.com/19405629/196905680-57432275-6539-44c5-abbb-754958a01dc5.png)
When clicking "Test rule" in "alerts tab" getting:
```
{
  ...
  "logs": [
    ...
    {
      "message": "Condition[0]: Query Result",
      "data": {
        "fromDataframe": true,
        "series": []                                          
      }
    },
    {
      "message": "Condition: Eval: false, Query Returned No Series (reduced to null/no value)",
      "data": null
    }
  ]
}
```

**Comment by ivanahuckova** [comment]
Hello @janisbiz. To help us investigate, could you please provide panel/dashboard JSON and query from query inspector.

**Comment by janisbiz** [comment]
@ivanahuckova I can provide it only with obscured values due to my company policy. If that's fine, let me know.

**Comment by ivanahuckova** [comment]
Yes it is absolutely fine! Thank you.

**Comment by janisbiz** [comment]
@ivanahuckova here you go:
```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "datasource",
          "uid": "grafana"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 125,
  "iteration": 1666786114102,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "alert": {
        "alertRuleTags": {},
        "conditions": [
          {
            "evaluator": {
              "params": [
                3
              ],
              "type": "lt"
            },
            "operator": {
              "type": "and"
            },
            "query": {
              "params": [
                "ALERT",
                "3m",
                "now"
              ]
            },
            "reducer": {
              "params": [],
              "type": "sum"
            },
            "type": "query"
          }
        ],
        "executionErrorState": "alerting",
        "for": "3m",
        "frequency": "1m",
        "handler": 1,
        "name": "OBSCURED",
        "noDataState": "alerting",
        "notifications": []
      },
      "datasource": {
        "type": "OBSCURED",
        "uid": "OBSCURED"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "bars",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "normal"
            },
            "thresholdsStyle": {
              "mode": "area"
            }
          },
          "mappings": [],
          "max": 1,
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 0
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 22,
        "x": 0,
        "y": 0
      },
      "id": 13,
      "interval": "1m",
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltip": {
          "mode": "multi",
          "sort": "none"
        }
      },
      "pluginVersion": "8.1.1",
      "targets": [
        {
          "alias": "",
          "bucketAggs": [
            {
              "field": "FIELD",
              "id": "3",
              "settings": {
                "min_doc_count": "1",
                "order": "desc",
                "orderBy": "_term",
                "size": "0"
              },
              "type": "terms"
            },
            {
              "id": "4",
              "settings": {
                "interval": "auto",
                "min_doc_count": "0",
                "trimEdges": "0"
              },
              "type": "date_histogram"
            }
          ],
          "datasource": {
            "type": "OBSCURED",
            "uid": "OBSCURED"
          },
          "format": "table",
          "metrics": [
            {
              "field": "value",
              "id": "1",
              "type": "sum"
            }
          ],
          "query": "KEY1:VALUE1 AND KEY2:\"VALUE2\" AND KEY3:\"VALUE3\"",
          "queryType": "lucene",
          "refId": "ALERT",
          "timeField": "time"
        }
      ],
      "thresholds": [
        {
          "colorMode": "critical",
          "op": "lt",
          "value": 3,
          "visible": true
        }
      ],
      "title": "OBSCURED",
      "type": "timeseries"
    }
  ],
  "refresh": "",
  "schemaVersion": 36,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "OBSCURED",
  "uid": "OBSCURED",
  "version": 5,
  "weekStart": ""
}
```

**Comment by maxwellvarner** [comment]
I too am experiencing this issue. I am using grafana OSS 9.1.8, but see the same in 9.2.2 with the opensearch plugin version 2.0.3. 

It appears from my grafana container logs that the alert queries are not respecting some of the values configured in the datasource. I expect see the index of [cds_proxies-]YYYY.MM.DD being used as it is configured in the datasource.
<img width="834" alt="Screen Shot 2022-11-02 at 12 43 54 PM" src="https://user-images.githubusercontent.com/93388319/199550407-ed881435-ae35-4e90-b9c4-1371587d5683.png">

but when I check the logs after running the queries from the Alerts tab I see that it is attempting to use a different index
<img width="1721" alt="Screen Shot 2022-11-02 at 12 54 20 PM" src="https://user-images.githubusercontent.com/93388319/199552424-2eac5fa9-9c22-490b-98f7-003068f4c780.png">

Output in grafana logs:
`logger=plugin.grafana-opensearch-datasource t=2022-11-02T16:25:11.322770919Z level=info msg="Creating new client" PPLindex=logstash-* indices=logstash-2022.11.02 timeField=@timestamp version=5.6.0`


These values from the datasource appear to be respected when I simply create a new panel for viewing only purposes.
<img width="1720" alt="Screen Shot 2022-11-02 at 12 52 41 PM" src="https://user-images.githubusercontent.com/93388319/199552031-7725f798-47ec-493d-8f47-5fcfe0c380fc.png">

**Comment by svennergr** [comment]
Thanks @maxwellvarner. I see that you are using the datasource to query an ElasticSearch. Could you provide the exact version of that ElasticSearch?

@janisbiz Are you using the datasource to query ElasticSearch as well, or any other database? Would be great to get that version too.

Thanks!

**Comment by svennergr** [comment]
@maxwellvarner / @janisbiz 

Sorry for the next ping. I discovered a root cause and will get a fix out.

**Comment by maxwellvarner** [comment]
I've attempted this against 2 different versions of Elasticsearch; versions 6.8.23 and 7.9

I got this information by running
`curl -u <username> -XGET 'https://<domain>:9200`

**Comment by janisbiz** [comment]
@svennergr not sure if it is still relevant, I am using OpenSearch `1.3.2`

**Comment by svennergr** [comment]
@janisbiz @maxwellvarner [OpenSearch v1.2.4 ](https://github.com/grafana/opensearch-datasource/releases/tag/v1.2.4)and [OpenSearch v2.0.4](https://github.com/grafana/opensearch-datasource/releases/tag/v2.0.4) have been released with a fix of this issue.

**Comment by janisbiz** [comment]
@svennergr just updated. The previous error is gone, but alerts are still not working. It seems like datasets are always returning `0`. Will take a look deeper to understand what's the problem.

@maxwellvarner please let us know how it is for you.

**Comment by svennergr** [comment]
@janisbiz tested in Grafana 8.5.13 and it was working for me:
![image](https://user-images.githubusercontent.com/8092184/199999795-c634f6f2-2f95-41b9-9f1b-a444237fb6f2.png)

**Comment by janisbiz** [comment]
@svennergr this is what I cam having for alert - with `sum`:
![image](https://user-images.githubusercontent.com/19405629/200002848-a61a5337-183b-4573-84d4-fe60bd22d955.png)

If I change to count - it is all good. Thus not sure why :thinking: I guess sum is not summing actual metric value maybe.

**Comment by maxwellvarner** [comment]
This appears to be working for me against both versions of elasticsearch mentioned above running grafana v9.1.8.

sum() appears to be returning the correct value for me. However, and perhaps I'm not understanding what count() is supposed to return, but those are different when I would think they should be the same given the query used. 

Alert Rule  - Results
![Screen Shot 2022-11-04 at 4 43 14 PM](https://user-images.githubusercontent.com/93388319/200072010-ec4b9880-a4d6-4e8a-8b7a-7c8f72e5a135.png)

Panel Results
![Screen Shot 2022-11-04 at 4 43 35 PM](https://user-images.githubusercontent.com/93388319/200072089-16387450-a0f5-4de5-ae1c-f7e674634afa.png)

**Comment by janisbiz** [comment]
@svennergr are you trying with elastic or OS? As I am using OS, it seems to be not working.

**Comment by janisbiz** [comment]
So, I re-created panel with same query, same alert (litereally everything the same) and it works now. I guess something was corrupted on my panel. :man_shrugging: 

Anyway - all good now. Thanks :tada:
