### ISSUE TITLE
support serverless opensearch

### ISSUE THREAD

**Issue by gabor** [grafana/opensearch-datasource#93]
the datasource should be modified to support serverless opensearch ( https://aws.amazon.com/opensearch-service/features/serverless/ ).

notable features:
- the user should be able to choose managed-or-serverless opensearch
- if the user chooses serverless opensearch:
    - sigv4 is mandatory
    - choosing the opensearch-version is not possible
    - no max-concurrent-shard-requests setting
    - PPL not allowed

(NOTE: the initial implementation will assume newest-grafana-version)

**Comment by svennergr** [comment]
Done in #92
